"""Add status and corridor_id to Train

Revision ID: 07a12dde8253
Revises: 1101ec3a1b93
Create Date: 2026-08-30 17:51:02.595476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a12dde8253'
down_revision: Union[str, Sequence[str], None] = '1101ec3a1b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='SCHEDULED'))
        batch_op.add_column(sa.Column('corridor_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_trains_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trains_status'), ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_trains_corridor_id_corridors'), 'corridors', ['corridor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trains_corridor_id_corridors'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trains_status'))
        batch_op.drop_index(batch_op.f('ix_trains_corridor_id'))
        batch_op.drop_column('corridor_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
