"""Add assigned_to and resolved_by to defect model

Revision ID: 1101ec3a1b93
Revises: eaedaf0e8c10
Create Date: 2026-08-30 17:29:29.903481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1101ec3a1b93'
down_revision: Union[str, Sequence[str], None] = 'eaedaf0e8c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_defects_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_defects_assigned_to_users'), 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_defects_resolved_by_users'), 'users', ['resolved_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_defects_resolved_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_defects_assigned_to_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_defects_assigned_to'))
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
