"""phase_23_reports_table

Revision ID: 947140c950b9
Revises: e7f10b2849c1
Create Date: 2026-08-30 22:49:55.599605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947140c950b9'
down_revision: Union[str, Sequence[str], None] = 'e7f10b2849c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_code', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('generated_by_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('summary_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_reports_corridor_id_corridors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_reports_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_report_code'), ['report_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_report_code'))

    op.drop_table('reports')
    # ### end Alembic commands ###
