"""create_railopt_database_schema

Revision ID: c0122322b6a7
Revises: 
Create Date: 2026-08-30 15:37:02.764069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0122322b6a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('prediction_type', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_predictions'))
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_predictions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_entity_type'), ['entity_type'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_entity_type'), ['entity_type'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('simulation_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_scenarios'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('trains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('train_number', sa.String(length=32), nullable=False),
    sa.Column('train_name', sa.String(length=128), nullable=False),
    sa.Column('train_type', sa.String(length=32), nullable=False),
    sa.Column('default_direction', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trains'))
    )
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trains_train_number'), ['train_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_code'), ['code'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('divisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_divisions_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions'))
    )
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_divisions_zone_id'), ['zone_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('simulation_date', sa.DateTime(), nullable=False),
    sa.Column('simulation_time', sa.String(length=32), nullable=False),
    sa.Column('speed_multiplier', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], name=op.f('fk_simulation_runs_scenario_id_simulation_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('simulation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_simulation_events_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_events'))
    )
    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_events_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_events_simulation_run_id'), ['simulation_run_id'], unique=False)

    op.create_table('stations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_stations_division_id_divisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations'))
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_stations_division_id'), ['division_id'], unique=False)

    op.create_table('corridors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_station_id', sa.String(length=36), nullable=False),
    sa.Column('end_station_id', sa.String(length=36), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('electrified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('distance_km >= 0', name=op.f('ck_corridors_chk_corridor_distance_positive')),
    sa.CheckConstraint('track_count > 0', name=op.f('ck_corridors_chk_corridor_track_count_positive')),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], name=op.f('fk_corridors_end_station_id_stations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], name=op.f('fk_corridors_start_station_id_stations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corridors'))
    )
    with op.batch_alter_table('corridors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corridors_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_corridors_end_station_id'), ['end_station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corridors_start_station_id'), ['start_station_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_code', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('station_id', sa.String(length=36), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('commission_date', sa.DateTime(), nullable=True),
    sa.Column('criticality_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('last_inspection_at', sa.DateTime(), nullable=True),
    sa.Column('next_inspection_at', sa.DateTime(), nullable=True),
    sa.Column('maintenance_due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('criticality_score >= 0 AND criticality_score <= 100', name=op.f('ck_assets_chk_asset_criticality_range')),
    sa.CheckConstraint('health_score >= 0 AND health_score <= 100', name=op.f('ck_assets_chk_asset_health_range')),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_assets_corridor_id_corridors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_assets_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_assets_station_id_stations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_asset_external_source_id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index('ix_assets_composite_dept_corridor', ['department_id', 'corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_criticality_score'), ['criticality_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    op.create_table('block_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('corridor_id', sa.String(length=36), nullable=False),
    sa.Column('planning_date', sa.DateTime(), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planning_horizon', sa.String(length=32), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('expected_train_delay', sa.Integer(), nullable=True),
    sa.Column('asset_availability_gain', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_block_plans_chk_block_plan_duration_positive')),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_block_plans_corridor_id_corridors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_plans'))
    )
    with op.batch_alter_table('block_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_plans_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_plans_plan_code'), ['plan_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_block_plans_planning_date'), ['planning_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_plans_status'), ['status'], unique=False)

    op.create_table('goods_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corridor_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('hour_start', sa.Integer(), nullable=False),
    sa.Column('hour_end', sa.Integer(), nullable=False),
    sa.Column('expected_goods_trains', sa.Float(), nullable=False),
    sa.Column('traffic_density', sa.String(length=16), nullable=False),
    sa.Column('movement_probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('movement_probability >= 0 AND movement_probability <= 1', name=op.f('ck_goods_forecasts_chk_goods_forecast_prob_range')),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_goods_forecasts_corridor_id_corridors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_forecasts'))
    )
    with op.batch_alter_table('goods_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_forecasts_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_forecasts_forecast_date'), ['forecast_date'], unique=False)

    op.create_table('optimization_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_code', sa.String(length=64), nullable=True),
    sa.Column('planning_horizon', sa.String(length=32), nullable=False),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective_config', sa.JSON(), nullable=True),
    sa.Column('constraint_config', sa.JSON(), nullable=True),
    sa.Column('solver_name', sa.String(length=64), nullable=False),
    sa.Column('solver_version', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_optimization_runs_corridor_id_corridors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_runs')),
    sa.UniqueConstraint('run_code', name=op.f('uq_optimization_runs_run_code'))
    )
    op.create_table('train_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('train_id', sa.String(length=36), nullable=False),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('station_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('actual_time', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('line', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_train_movements_corridor_id_corridors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_train_movements_station_id_stations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_train_movements_train_id_trains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_train_movements'))
    )
    with op.batch_alter_table('train_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_train_movements_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_movements_train_id'), ['train_id'], unique=False)

    op.create_table('train_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('train_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('line', sa.String(length=32), nullable=True),
    sa.Column('road', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_train_schedules_corridor_id_corridors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_train_schedules_station_id_stations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_train_schedules_train_id_trains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_train_schedules'))
    )
    with op.batch_alter_table('train_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_train_station_date', ['train_id', 'station_id', 'scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_arrival_time'), ['arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_departure_time'), ['departure_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_schedules_train_id'), ['train_id'], unique=False)

    op.create_table('asset_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('inspection_score', sa.Float(), nullable=True),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.Column('usage_score', sa.Float(), nullable=True),
    sa.Column('defect_score', sa.Float(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('defect_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_health_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_health'))
    )
    with op.batch_alter_table('asset_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_health_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_health_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('asset_risk_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_risk_predictions_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_risk_predictions'))
    )
    with op.batch_alter_table('asset_risk_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_risk_predictions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_risk_predictions_prediction_date'), ['prediction_date'], unique=False)

    op.create_table('block_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_plan_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], name=op.f('fk_block_approvals_block_plan_id_block_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_approvals'))
    )
    with op.batch_alter_table('block_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_approvals_block_plan_id'), ['block_plan_id'], unique=False)

    op.create_table('block_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_plan_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_train_id', sa.String(length=36), nullable=True),
    sa.Column('related_block_id', sa.String(length=36), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], name=op.f('fk_block_conflicts_block_plan_id_block_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_block_id'], ['block_plans.id'], name=op.f('fk_block_conflicts_related_block_id_block_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_train_id'], ['trains.id'], name=op.f('fk_block_conflicts_related_train_id_trains'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_conflicts'))
    )
    with op.batch_alter_table('block_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_conflicts_block_plan_id'), ['block_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_conflicts_conflict_type'), ['conflict_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_conflicts_resolved'), ['resolved'], unique=False)

    op.create_table('block_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_code', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=False),
    sa.Column('preferred_start_at', sa.DateTime(), nullable=False),
    sa.Column('preferred_end_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_block_requests_chk_block_request_duration_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_block_requests_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_block_requests_corridor_id_corridors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_block_requests_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_requests')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_block_request_external_source_id')
    )
    with op.batch_alter_table('block_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_requests_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_requests_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_requests_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_requests_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_requests_request_code'), ['request_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_block_requests_requested_date'), ['requested_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_requests_status'), ['status'], unique=False)

    op.create_table('defects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('defect_code', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('detected_by', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('safety_impact', sa.Float(), nullable=False),
    sa.Column('operational_impact', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('operational_impact >= 0 AND operational_impact <= 100', name=op.f('ck_defects_chk_defect_operational_range')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name=op.f('ck_defects_chk_defect_risk_range')),
    sa.CheckConstraint('safety_impact >= 0 AND safety_impact <= 100', name=op.f('ck_defects_chk_defect_safety_range')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_defects_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_defects_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defects')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_defect_external_source_id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_defects_asset_severity_status', ['asset_id', 'severity', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_defect_code'), ['defect_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_defects_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_target_resolution_date'), ['target_resolution_date'], unique=False)

    op.create_table('feeders',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_feeders_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_feeders'))
    )
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('inspection_type', sa.String(length=64), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('inspector', sa.String(length=64), nullable=False),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('next_inspection_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_inspections_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_inspections_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspection_date'), ['inspection_date'], unique=False)

    op.create_table('maintenance_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_code', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completion_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('safety_impact', sa.Float(), nullable=False),
    sa.Column('train_impact', sa.Float(), nullable=False),
    sa.Column('block_required', sa.Boolean(), nullable=False),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.Column('preferred_start_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_end_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_team', sa.String(length=64), nullable=True),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('criticality >= 0 AND criticality <= 100', name=op.f('ck_maintenance_tasks_chk_maint_criticality_range')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_maintenance_tasks_chk_maint_duration_positive')),
    sa.CheckConstraint('safety_impact >= 0 AND safety_impact <= 100', name=op.f('ck_maintenance_tasks_chk_maint_safety_range')),
    sa.CheckConstraint('train_impact >= 0 AND train_impact <= 100', name=op.f('ck_maintenance_tasks_chk_maint_train_impact_range')),
    sa.CheckConstraint('urgency >= 0 AND urgency <= 100', name=op.f('ck_maintenance_tasks_chk_maint_urgency_range')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maintenance_tasks_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_maintenance_tasks_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_tasks')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_maintenance_external_source_id')
    )
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_maint_tasks_asset_dept_status', ['asset_id', 'department_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_block_required'), ['block_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_scheduled_start_at'), ['scheduled_start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_task_code'), ['task_code'], unique=True)

    op.create_table('ohe_assets',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_ohe_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_ohe_assets'))
    )
    op.create_table('optimization_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('optimization_run_id', sa.String(length=36), nullable=False),
    sa.Column('block_plan_id', sa.String(length=36), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('maintenance_priority_coverage', sa.Float(), nullable=True),
    sa.Column('asset_availability_gain', sa.Float(), nullable=True),
    sa.Column('train_delay', sa.Float(), nullable=True),
    sa.Column('downtime_reduction', sa.Float(), nullable=True),
    sa.Column('shared_block_bonus', sa.Float(), nullable=True),
    sa.Column('result_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], name=op.f('fk_optimization_results_block_plan_id_block_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], name=op.f('fk_optimization_results_optimization_run_id_optimization_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_results'))
    )
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_results_optimization_run_id'), ['optimization_run_id'], unique=False)

    op.create_table('point_machines',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('point_type', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_point_machines_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_point_machines'))
    )
    op.create_table('signal_assets',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_signal_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_signal_assets'))
    )
    op.create_table('substations',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_substations_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_substations'))
    )
    op.create_table('telecom_assets',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('system_type', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_telecom_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_telecom_assets'))
    )
    op.create_table('track_assets',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('kilometer_from', sa.Float(), nullable=False),
    sa.Column('kilometer_to', sa.Float(), nullable=False),
    sa.Column('track_type', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_track_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_track_assets'))
    )
    op.create_table('transformers',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_transformers_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_transformers'))
    )
    op.create_table('block_tasks',
    sa.Column('block_plan_id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_task_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], name=op.f('fk_block_tasks_block_plan_id_block_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], name=op.f('fk_block_tasks_maintenance_task_id_maintenance_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_plan_id', 'maintenance_task_id', name=op.f('pk_block_tasks'))
    )
    op.create_table('maintenance_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_task_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maintenance_history_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], name=op.f('fk_maintenance_history_maintenance_task_id_maintenance_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_history'))
    )
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_history_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_history_maintenance_task_id'), ['maintenance_task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_history_maintenance_task_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_history_event_time'))

    op.drop_table('maintenance_history')
    op.drop_table('block_tasks')
    op.drop_table('transformers')
    op.drop_table('track_assets')
    op.drop_table('telecom_assets')
    op.drop_table('substations')
    op.drop_table('signal_assets')
    op.drop_table('point_machines')
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_results_optimization_run_id'))

    op.drop_table('optimization_results')
    op.drop_table('ohe_assets')
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_task_code'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_scheduled_start_at'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_department_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_block_required'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_asset_id'))
        batch_op.drop_index('ix_maint_tasks_asset_dept_status')

    op.drop_table('maintenance_tasks')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_inspection_date'))
        batch_op.drop_index(batch_op.f('ix_inspections_asset_id'))

    op.drop_table('inspections')
    op.drop_table('feeders')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_target_resolution_date'))
        batch_op.drop_index(batch_op.f('ix_defects_status'))
        batch_op.drop_index(batch_op.f('ix_defects_severity'))
        batch_op.drop_index(batch_op.f('ix_defects_risk_score'))
        batch_op.drop_index(batch_op.f('ix_defects_detected_at'))
        batch_op.drop_index(batch_op.f('ix_defects_department_id'))
        batch_op.drop_index(batch_op.f('ix_defects_defect_code'))
        batch_op.drop_index('ix_defects_asset_severity_status')
        batch_op.drop_index(batch_op.f('ix_defects_asset_id'))

    op.drop_table('defects')
    with op.batch_alter_table('block_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_requests_status'))
        batch_op.drop_index(batch_op.f('ix_block_requests_requested_date'))
        batch_op.drop_index(batch_op.f('ix_block_requests_request_code'))
        batch_op.drop_index(batch_op.f('ix_block_requests_priority'))
        batch_op.drop_index(batch_op.f('ix_block_requests_department_id'))
        batch_op.drop_index(batch_op.f('ix_block_requests_corridor_id'))
        batch_op.drop_index(batch_op.f('ix_block_requests_asset_id'))

    op.drop_table('block_requests')
    with op.batch_alter_table('block_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_conflicts_resolved'))
        batch_op.drop_index(batch_op.f('ix_block_conflicts_conflict_type'))
        batch_op.drop_index(batch_op.f('ix_block_conflicts_block_plan_id'))

    op.drop_table('block_conflicts')
    with op.batch_alter_table('block_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_approvals_block_plan_id'))

    op.drop_table('block_approvals')
    with op.batch_alter_table('asset_risk_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_risk_predictions_prediction_date'))
        batch_op.drop_index(batch_op.f('ix_asset_risk_predictions_asset_id'))

    op.drop_table('asset_risk_predictions')
    with op.batch_alter_table('asset_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_health_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_asset_health_asset_id'))

    op.drop_table('asset_health')
    with op.batch_alter_table('train_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_train_schedules_train_id'))
        batch_op.drop_index(batch_op.f('ix_train_schedules_station_id'))
        batch_op.drop_index(batch_op.f('ix_train_schedules_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_train_schedules_departure_time'))
        batch_op.drop_index(batch_op.f('ix_train_schedules_corridor_id'))
        batch_op.drop_index(batch_op.f('ix_train_schedules_arrival_time'))
        batch_op.drop_index('ix_schedules_train_station_date')

    op.drop_table('train_schedules')
    with op.batch_alter_table('train_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_train_movements_train_id'))
        batch_op.drop_index(batch_op.f('ix_train_movements_corridor_id'))

    op.drop_table('train_movements')
    op.drop_table('optimization_runs')
    with op.batch_alter_table('goods_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_forecasts_forecast_date'))
        batch_op.drop_index(batch_op.f('ix_goods_forecasts_corridor_id'))

    op.drop_table('goods_forecasts')
    with op.batch_alter_table('block_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_plans_status'))
        batch_op.drop_index(batch_op.f('ix_block_plans_planning_date'))
        batch_op.drop_index(batch_op.f('ix_block_plans_plan_code'))
        batch_op.drop_index(batch_op.f('ix_block_plans_corridor_id'))

    op.drop_table('block_plans')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_station_id'))
        batch_op.drop_index(batch_op.f('ix_assets_department_id'))
        batch_op.drop_index(batch_op.f('ix_assets_criticality_score'))
        batch_op.drop_index(batch_op.f('ix_assets_corridor_id'))
        batch_op.drop_index('ix_assets_composite_dept_corridor')
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_code'))

    op.drop_table('assets')
    with op.batch_alter_table('corridors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corridors_start_station_id'))
        batch_op.drop_index(batch_op.f('ix_corridors_end_station_id'))
        batch_op.drop_index(batch_op.f('ix_corridors_code'))

    op.drop_table('corridors')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_division_id'))
        batch_op.drop_index(batch_op.f('ix_stations_code'))

    op.drop_table('stations')
    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_events_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_events_event_time'))

    op.drop_table('simulation_events')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_scenario_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisions_zone_id'))
        batch_op.drop_index(batch_op.f('ix_divisions_code'))

    op.drop_table('divisions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_code'))

    op.drop_table('zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trains_train_number'))

    op.drop_table('trains')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    op.drop_table('simulation_scenarios')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_entity_type'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_entity_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_entity_type'))
        batch_op.drop_index(batch_op.f('ix_ai_predictions_entity_id'))

    op.drop_table('ai_predictions')
    # ### end Alembic commands ###
