"""Phase 15 Train Impact Engine

Revision ID: d19219408f9a
Revises: f56d887792b9
Create Date: 2026-08-30 19:36:14.293597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19219408f9a'
down_revision: Union[str, Sequence[str], None] = 'f56d887792b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_impacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=36), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=False),
    sa.Column('train_id', sa.String(length=36), nullable=False),
    sa.Column('impact_type', sa.String(length=32), nullable=False),
    sa.Column('estimated_delay_minutes', sa.Float(), nullable=False),
    sa.Column('maximum_delay_minutes', sa.Float(), nullable=False),
    sa.Column('passenger_impact', sa.Integer(), nullable=False),
    sa.Column('goods_impact', sa.String(length=64), nullable=True),
    sa.Column('operational_impact', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block_requests.id'], name=op.f('fk_train_impacts_block_id_block_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_train_impacts_corridor_id_corridors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_train_impacts_train_id_trains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_train_impacts'))
    )
    with op.batch_alter_table('train_impacts', schema=None) as batch_op:
        batch_op.create_index('ix_train_impact_block_train', ['block_id', 'train_id'], unique=False)
        batch_op.create_index('ix_train_impact_corridor_date', ['corridor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_impacts_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_impacts_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_impacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_train_impacts_train_id'), ['train_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train_impacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_train_impacts_train_id'))
        batch_op.drop_index(batch_op.f('ix_train_impacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_train_impacts_corridor_id'))
        batch_op.drop_index(batch_op.f('ix_train_impacts_block_id'))
        batch_op.drop_index('ix_train_impact_corridor_date')
        batch_op.drop_index('ix_train_impact_block_train')

    op.drop_table('train_impacts')
    # ### end Alembic commands ###
