"""Phase 16 Block Conflict Engine updates

Revision ID: d2ec699d6bc4
Revises: d19219408f9a
Create Date: 2026-08-30 19:53:12.788883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ec699d6bc4'
down_revision: Union[str, Sequence[str], None] = 'd19219408f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_request_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('corridor_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolution_suggestion', sa.Text(), nullable=True))
        batch_op.alter_column('block_plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_block_conflicts_block_request_id'), ['block_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_conflicts_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_conflicts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_conflicts_start_time'), ['start_time'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_block_conflicts_corridor_id_corridors'), 'corridors', ['corridor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_block_conflicts_block_request_id_block_requests'), 'block_requests', ['block_request_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_conflicts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_block_conflicts_block_request_id_block_requests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_block_conflicts_corridor_id_corridors'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_block_conflicts_start_time'))
        batch_op.drop_index(batch_op.f('ix_block_conflicts_severity'))
        batch_op.drop_index(batch_op.f('ix_block_conflicts_corridor_id'))
        batch_op.drop_index(batch_op.f('ix_block_conflicts_block_request_id'))
        batch_op.alter_column('block_plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('resolution_suggestion')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('corridor_id')
        batch_op.drop_column('block_request_id')

    # ### end Alembic commands ###
