"""Phase 12 Block Request Extensions

Revision ID: fbf078f1a63f
Revises: 07a12dde8253
Create Date: 2026-08-30 18:20:24.398641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf078f1a63f'
down_revision: Union[str, Sequence[str], None] = '07a12dde8253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_request_tasks',
    sa.Column('block_request_id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_task_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_request_id'], ['block_requests.id'], name=op.f('fk_block_request_tasks_block_request_id_block_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], name=op.f('fk_block_request_tasks_maintenance_task_id_maintenance_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_request_id', 'maintenance_task_id', name=op.f('pk_block_request_tasks'))
    )
    with op.batch_alter_table('block_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_requests', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('submitted_at')

    op.drop_table('block_request_tasks')
    # ### end Alembic commands ###
